package com.sqz.writingboard.ui.theme

import androidx.compose.ui.graphics.Color

val RedForManual = Color(0xBEE21717)
val PurpleForManual = Color(0xFF816EB8)
val Blue = Color(0xFF56BFE7)
val Pink = Color(0xFFE29CAA)
val White = Color(0xFFE7E7E7)
val Purple = Color(0xFF6650a4)
val PinkText = Color(0xFF7D5260)

//For below Android 12 color
val theme_light_primary = Color(0xFF215FA6)
val theme_light_onPrimary = Color(0xFFFFFFFF)
val theme_light_primaryContainer = Color(0xFFD5E3FF)
val theme_light_onPrimaryContainer = Color(0xFF001C3B)
val theme_light_secondary = Color(0xFF555F71)
val theme_light_onSecondary = Color(0xFFFFFFFF)
val theme_light_secondaryContainer = Color(0xFFD9E3F8)
val theme_light_onSecondaryContainer = Color(0xFF121C2B)
val theme_light_tertiary = Color(0xFF6E5676)
val theme_light_onTertiary = Color(0xFFFFFFFF)
val theme_light_tertiaryContainer = Color(0xFFF8D8FF)
val theme_light_onTertiaryContainer = Color(0xFF27132F)
val theme_light_error = Color(0xFFBA1A1A)
val theme_light_errorContainer = Color(0xFFFFDAD6)
val theme_light_onError = Color(0xFFFFFFFF)
val theme_light_onErrorContainer = Color(0xFF410002)
val theme_light_background = Color(0xFFFDFBFF)
val theme_light_onBackground = Color(0xFF1A1C1E)
val theme_light_surface = Color(0xFFFDFBFF)
val theme_light_onSurface = Color(0xFF1A1C1E)
val theme_light_surfaceVariant = Color(0xFFE0E2EC)
val theme_light_onSurfaceVariant = Color(0xFF43474E)
val theme_light_outline = Color(0xFF74777F)
val theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val theme_light_inverseSurface = Color(0xFF2F3033)
val theme_light_inversePrimary = Color(0xFFA6C8FF)
val theme_light_shadow = Color(0xFF000000)
val theme_light_surfaceTint = Color(0xFF215FA6)
val theme_light_outlineVariant = Color(0xFFC4C6CF)
val theme_light_scrim = Color(0xFF000000)

val theme_dark_primary = Color(0xFFA6C8FF)
val theme_dark_onPrimary = Color(0xFF003060)
val theme_dark_primaryContainer = Color(0xFF004787)
val theme_dark_onPrimaryContainer = Color(0xFFD5E3FF)
val theme_dark_secondary = Color(0xFFBDC7DC)
val theme_dark_onSecondary = Color(0xFF273141)
val theme_dark_secondaryContainer = Color(0xFF3D4758)
val theme_dark_onSecondaryContainer = Color(0xFFD9E3F8)
val theme_dark_tertiary = Color(0xFFDBBDE2)
val theme_dark_onTertiary = Color(0xFF3E2846)
val theme_dark_tertiaryContainer = Color(0xFF553F5D)
val theme_dark_onTertiaryContainer = Color(0xFFF8D8FF)
val theme_dark_error = Color(0xFFFFB4AB)
val theme_dark_errorContainer = Color(0xFF93000A)
val theme_dark_onError = Color(0xFF690005)
val theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val theme_dark_background = Color(0xFF1A1C1E)
val theme_dark_onBackground = Color(0xFFE3E2E6)
val theme_dark_surface = Color(0xFF1A1C1E)
val theme_dark_onSurface = Color(0xFFE3E2E6)
val theme_dark_surfaceVariant = Color(0xFF43474E)
val theme_dark_onSurfaceVariant = Color(0xFFC4C6CF)
val theme_dark_outline = Color(0xFF8D9199)
val theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val theme_dark_inverseSurface = Color(0xFFE3E2E6)
val theme_dark_inversePrimary = Color(0xFF215FA6)
val theme_dark_shadow = Color(0xFF000000)
val theme_dark_surfaceTint = Color(0xFFA6C8FF)
val theme_dark_outlineVariant = Color(0xFF43474E)
val theme_dark_scrim = Color(0xFF000000)